[project]
name = "myoecho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.2.6",
    "pip>=25.2",
    "scikit-image>=0.25.2",
    "torch==2.5.1",
    "torchvision==0.20.1",
]
